USE `quiz_arena`;

-- Seed at least 10 for each difficulty across categories (minimal example; extend as needed)
INSERT INTO questions (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
-- Science easy (10)
('science','easy','What planet is known as the Red Planet?','Earth','Mars','Venus','Jupiter','B'),
('science','easy','H2O is the chemical formula for?','Oxygen','Hydrogen','Water','Helium','C'),
('science','easy','What gas do plants breathe in?','Oxygen','Carbon Dioxide','Nitrogen','Helium','B'),
('science','easy','What force pulls objects toward Earth?','Magnetism','Friction','Gravity','Inertia','C'),
('science','easy','What organ pumps blood?','Liver','Lungs','Heart','Brain','C'),
('science','easy','The sun is a?','Planet','Star','Comet','Asteroid','B'),
('science','easy','What do bees collect?','Water','Pollen','Leaves','Soil','B'),
('science','easy','What is freezing point of water (°C)?','0','10','32','-10','A'),
('science','easy','What part of plant makes food?','Root','Stem','Leaf','Flower','C'),
('science','easy','Which metal is liquid at room temp?','Mercury','Iron','Gold','Copper','A'),
-- Sports easy (10)
('sports','easy','How many players in a soccer team on field?','9','10','11','12','C'),
('sports','easy','What is the NBA?','Baseball','Basketball','Football','Hockey','B'),
('sports','easy','Tennis uses what?','Bat','Stick','Racket','Club','C'),
('sports','easy','Olympics occur every?','2 years','3 years','4 years','5 years','C'),
('sports','easy','Cricket ball color traditionally?','White','Red','Blue','Green','B'),
('sports','easy','Goalkeeper uses hands in?','Rugby','Soccer','Basketball','Hockey','B'),
('sports','easy','Strike is in?','Baseball','Bowling','Soccer','Tennis','B'),
('sports','easy','What sport has end zone?','Soccer','American Football','Tennis','Golf','B'),
('sports','easy','Marathon distance ~?','10km','21km','42km','60km','C'),
('sports','easy','Birdie is in?','Tennis','Badminton','Cricket','Rugby','B'),
-- GK easy (10)
('gk','easy','Capital of France?','London','Berlin','Paris','Rome','C'),
('gk','easy','Largest ocean?','Atlantic','Pacific','Indian','Arctic','B'),
('gk','easy','How many continents?','5','6','7','8','C'),
('gk','easy','Currency of Japan?','Yen','Won','Rupee','Dollar','A'),
('gk','easy','Largest planet?','Earth','Mars','Jupiter','Saturn','C'),
('gk','easy','Who wrote Hamlet?','Shakespeare','Hemingway','Tolkien','Austen','A'),
('gk','easy','Fastest land animal?','Cheetah','Lion','Horse','Tiger','A'),
('gk','easy','Mount Everest is in?','India','Nepal','China','Bhutan','B'),
('gk','easy','Which is a mammal?','Frog','Dolphin','Shark','Eagle','B'),
('gk','easy','Primary colors are?','Red,Green,Blue','Red,Blue,Yellow','Green,Yellow,Blue','Red,Yellow,Black','B'),
-- Video games easy (10)
('video_games','easy','Mascot of Nintendo?','Sonic','Mario','Pikachu','Link','B'),
('video_games','easy','Creeper is from?','Minecraft','Fortnite','Roblox','Apex','A'),
('video_games','easy','Master Chief is from?','Halo','Gears','Destiny','Overwatch','A'),
('video_games','easy','Company behind PlayStation?','Nintendo','Microsoft','Sony','Sega','C'),
('video_games','easy','Poké Balls catch?','Monsters','Animals','Aliens','Cars','A'),
('video_games','easy','Hyrule is in?','Zelda','Mario','Metroid','Kirby','A'),
('video_games','easy','Blue blur is?','Sonic','Mario','Crash','Spyro','A'),
('video_games','easy','Battle Royale famous?','Rocket League','Fortnite','Stardew','Skyrim','B'),
('video_games','easy','Tetris shapes called?','Tetrominoes','Blocks','Polys','Pieces','A'),
('video_games','easy','Among Us role?','Impostor','Spy','Agent','Guardian','A');

-- Medium (10 each)
INSERT INTO questions (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
-- Science medium
('science','medium','Which particle has a negative charge?','Proton','Neutron','Electron','Positron','C'),
('science','medium','What is the speed of light (km/s)?','300,000','30,000','3,000','300','A'),
('science','medium','DNA stands for?','Deoxyribonucleic Acid','Dinucleic Acid','Deoxyribose Acid','Dioxyribonucleic Acid','A'),
('science','medium','Which vitamin is produced by sunlight?','A','C','D','K','C'),
('science','medium','pH less than 7 means?','Neutral','Acidic','Basic','Salty','B'),
('science','medium','Earths core is mostly?','Iron and Nickel','Gold','Silver','Copper','A'),
('science','medium','Unit of electric resistance?','Volt','Ampere','Ohm','Watt','C'),
('science','medium','Chlorophyll absorbs mostly?','Green Light','Blue and Red','Yellow','Infrared','B'),
('science','medium','Largest organ in human body?','Heart','Skin','Liver','Lungs','B'),
('science','medium','First law of motion by?','Newton','Einstein','Galileo','Maxwell','A'),
-- Sports medium
('sports','medium','How many minutes in a soccer match (regular time)?','80','90','100','120','B'),
('sports','medium','Grand Slam is term in?','Tennis','Golf','Cricket','Hockey','A'),
('sports','medium','How many players in a basketball team on court?','4','5','6','7','B'),
('sports','medium','Offside rule belongs to?','Basketball','Soccer','Cricket','Rugby','B'),
('sports','medium','Wimbledon played on which surface?','Clay','Grass','Hard','Carpet','B'),
('sports','medium','Hat-trick means?','3 goals','3 saves','3 fouls','3 subs','A'),
('sports','medium','LBW is in?','Baseball','Cricket','Hockey','Rugby','B'),
('sports','medium','NHL is league for?','Baseball','Basketball','Hockey','Football','C'),
('sports','medium','How many innings in baseball (standard)?','7','8','9','10','C'),
('sports','medium','Baton is used in?','Tennis','Relay Race','Fencing','Rowing','B'),
-- GK medium
('gk','medium','Which country has the maple leaf flag?','USA','Canada','UK','Australia','B'),
('gk','medium','Which desert is largest hot desert?','Gobi','Sahara','Kalahari','Arabian','B'),
('gk','medium','Who painted Mona Lisa?','Van Gogh','Da Vinci','Picasso','Rembrandt','B'),
('gk','medium','Smallest prime number?','0','1','2','3','C'),
('gk','medium','Which language has most native speakers?','English','Spanish','Mandarin Chinese','Hindi','C'),
('gk','medium','The tallest building is in?','New York','Dubai','Shanghai','Tokyo','B'),
('gk','medium','Which year did WW2 end?','1943','1944','1945','1946','C'),
('gk','medium','Which continent is Egypt in?','Asia','Africa','Europe','Oceania','B'),
('gk','medium','E = mc^2 describes?','Thermodynamics','Relativity','Quantum','Optics','B'),
('gk','medium','Capital of Australia?','Sydney','Melbourne','Canberra','Perth','C'),
-- Video games medium
('video_games','medium','What is the currency in The Witcher 3?','Septim','Orens','Crowns','Gil','C'),
('video_games','medium','First Pokémon in Pokédex?','Pikachu','Bulbasaur','Charmander','Squirtle','B'),
('video_games','medium','Metal Gear creator?','Miyamoto','Kojima','Sakurai','Yamauchi','B'),
('video_games','medium','Overwatch class not present?','Tank','Support','Mage','Damage','C'),
('video_games','medium','Call of Duty studio?','Infinity Ward','Valve','Bungie','CDPR','A'),
('video_games','medium','Hollow Knight role?','The Knight','The King','The Bug','The Hunter','A'),
('video_games','medium','Zelda instrument in OOT?','Harp','Ocarina','Flute','Lyre','B'),
('video_games','medium','Blue shell appears in?','Fortnite','Mario Kart','Apex','CS:GO','B'),
('video_games','medium','RPG stat typically not seen?','HP','MP','KD','STR','C'),
('video_games','medium','World of Warcraft races are in?','Azeroth','Tamriel','Hyrule','San Andreas','A');

-- Hard (10 each)
INSERT INTO questions (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
-- Science hard
('science','hard','Avogadros number is approx?','6.02e22','6.02e23','6.02e24','6.02e25','B'),
('science','hard','Which bond shares electron pairs?','Ionic','Covalent','Metallic','Hydrogen','B'),
('science','hard','SI unit of power?','Watt','Joule','Newton','Pascal','A'),
('science','hard','Greenhouse gas with highest concentration?','CO2','CH4','N2O','O3','A'),
('science','hard','The Heisenberg principle relates to?','Momentum & Position','Energy & Mass','Charge & Spin','Time & Space','A'),
('science','hard','Mitochondria produce?','Proteins','Energy (ATP)','DNA','Hormones','B'),
('science','hard','Acid rain mainly due to?','SO2 and NOx','CO2 only','CO only','O3 only','A'),
('science','hard','Unit of frequency?','Hertz','Tesla','Henry','Farad','A'),
('science','hard','Which is a noble gas?','Chlorine','Argon','Nitrogen','Hydrogen','B'),
('science','hard','Which telescope detects radio waves?','Optical','Radio','X-ray','Infrared','B'),
-- Sports hard
('sports','hard','First modern Olympics year?','1896','1900','1912','1920','A'),
('sports','hard','Number of squares on a chessboard?','64','72','81','100','A'),
('sports','hard','Cricket over has how many balls?','5','6','8','10','B'),
('sports','hard','Rings in Olympic symbol?','4','5','6','7','B'),
('sports','hard','T20 means how many overs per side?','10','20','25','50','B'),
('sports','hard','Yellow jersey is in?','F1','Tour de France','La Liga','NBA','B'),
('sports','hard','Tennis Grand Slams per year?','2','3','4','5','C'),
('sports','hard','FIFA World Cup cycle?','2 years','3 years','4 years','5 years','C'),
('sports','hard','How many players in rugby union?','13','14','15','16','C'),
('sports','hard','Snooker balls total (standard)?','15','22','21','20','B'),
-- GK hard
('gk','hard','Largest country by area?','USA','China','Russia','Canada','C'),
('gk','hard','Author of 1984?','Orwell','Huxley','Bradbury','Atwood','A'),
('gk','hard','Nobel Prize city (Peace)?','Stockholm','Oslo','Copenhagen','Geneva','B'),
('gk','hard','First man in space?','Yuri Gagarin','Neil Armstrong','Alan Shepard','John Glenn','A'),
('gk','hard','Currency of Switzerland?','Euro','Franc','Krone','Pound','B'),
('gk','hard','GDP stands for?','Gross Domestic Product','General Domestic Product','Gross Demand Product','Global Domestic Product','A'),
('gk','hard','Suez Canal connects?','Med & Red Sea','Black & Caspian','Red & Arabian','Med & Black','A'),
('gk','hard','Capital of Brazil?','Rio','Sao Paulo','Brasilia','Salvador','C'),
('gk','hard','UN founded in year?','1919','1945','1950','1960','B'),
('gk','hard','Author of Iliad?','Homer','Virgil','Sophocles','Aeschylus','A'),
-- Video games hard
('video_games','hard','Dark Souls creator studio?','FromSoftware','Capcom','Konami','Sega','A'),
('video_games','hard','Half-Life main protagonist?','Gordon Freeman','Alyx Vance','Isaac Clarke','Marcus Fenix','A'),
('video_games','hard','Skyrim province is?','Cyrodiil','Skyrim','Morrowind','High Rock','B'),
('video_games','hard','Splatoon ink color mechanic is for?','Running speed','Swimming and speed','Jump height','Stealth','B'),
('video_games','hard','Portal companion cube is?','Weighted','Charged','Explosive','Magnetic','A'),
('video_games','hard','Dota 2 map lanes?','2','3','4','5','B'),
('video_games','hard','Metroid protagonist?','Samus Aran','Master Chief','Solid Snake','Lara Croft','A'),
('video_games','hard','League of Legends max team size?','3','4','5','6','C'),
('video_games','hard','Bloodborne city is called?','Yharnam','Lothric','Rivendell','Rapture','A'),
('video_games','hard','Chrono Trigger time travel device?','Time Gate','Epoch','Portal Gun','DeLorean','B');

-- Extreme (10 each)
INSERT INTO questions (category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
-- Science extreme
('science','extreme','Schrödingers equation governs?','Classical Mechanics','Quantum Mechanics','Relativity','Thermodynamics','B'),
('science','extreme','Planck constant symbol?','k','h','c','G','B'),
('science','extreme','Which is not a fundamental force?','Gravity','Electromagnetism','Friction','Weak','C'),
('science','extreme','RNA sugar is?','Deoxyribose','Ribose','Glucose','Sucrose','B'),
('science','extreme','Unit for magnetic flux?','Weber','Tesla','Gauss','Henry','A'),
('science','extreme','Spectral lines identify?','Mass','Charge','Elements','Volume','C'),
('science','extreme','Who proposed general relativity?','Newton','Einstein','Maxwell','Bohr','B'),
('science','extreme','pKa relates to?','Acid strength','Base strength','Boiling point','Viscosity','A'),
('science','extreme','What is a quasar?','Galaxy cluster','Young star','Active galactic nucleus','Nebula','C'),
('science','extreme','Boltzmann constant relates to?','Pressure','Entropy/Temperature','Velocity','Charge','B'),
-- Sports extreme
('sports','extreme','Triple-double is in?','Soccer','Basketball','Cricket','Tennis','B'),
('sports','extreme','Which country has most FIFA World Cups?','Germany','Argentina','Brazil','Italy','C'),
('sports','extreme','Ice hockey match periods?','2','3','4','5','B'),
('sports','extreme','Boxing weight class not typical?','Featherweight','Middleweight','Super Tall','Lightweight','C'),
('sports','extreme','Grand Slam in golf majors?','4','5','3','2','A'),
('sports','extreme','Term bogey belongs to?','Tennis','Golf','Cricket','Baseball','B'),
('sports','extreme','Red card means?','Warning','Ejection','Goal','Timeout','B'),
('sports','extreme','Which country hosts La Liga?','Italy','Spain','France','Portugal','B'),
('sports','extreme','Heptathlon events count?','5','7','9','10','B'),
('sports','extreme','Which is not a position in baseball?','Shortstop','Goaltender','Catcher','Pitcher','B'),
-- GK extreme
('gk','extreme','Capital of Kazakhstan?','Astana','Almaty','Tashkent','Baku','A'),
('gk','extreme','Currency of South Korea?','Yen','Won','Yuan','Baht','B'),
('gk','extreme','Largest moon of Saturn?','Europa','Ganymede','Titan','Callisto','C'),
('gk','extreme','Prime Meridian passes through?','Paris','London','Berlin','Madrid','B'),
('gk','extreme','Author of Don Quixote?','Cervantes','Borges','Lorca','Neruda','A'),
('gk','extreme','UN headquarter city?','Geneva','New York','Brussels','Paris','B'),
('gk','extreme','Language not Indo-European?','Hindi','Finnish','Persian','Greek','B'),
('gk','extreme','Which is a Baltic state?','Belarus','Latvia','Moldova','Serbia','B'),
('gk','extreme','Nile flows into which sea?','Red Sea','Mediterranean','Black Sea','Arabian','B'),
('gk','extreme','Which mountain is in Japan?','Fuji','Kilimanjaro','Denali','Everest','A'),
-- Video games extreme
('video_games','extreme','First home video game console?','NES','Odyssey','Atari 2600','Intellivision','B'),
('video_games','extreme','FFVII main antagonist?','Kefka','Sephiroth','Ardyn','Ultimecia','B'),
('video_games','extreme','Undertale developer?','Toby Fox','Edmund McMillen','Eric Barone','Yoko Taro','A'),
('video_games','extreme','Resident Evil corporation?','Umbrella','ShinRa','Aperture','Abstergo','A'),
('video_games','extreme','Deus Ex augmentations are?','Cybernetic','Magical','Biological only','Alien','A'),
('video_games','extreme','Chrono Cross element system called?','Materia','Elements','Runes','Glyphs','B'),
('video_games','extreme','Papers, Please role?','Inspector','Doctor','Police','Pilot','A'),
('video_games','extreme','Celeste focuses on?','Racing','Platforming','Fighting','Strategy','B'),
('video_games','extreme','Mass Effect ship name?','Normandy','Serenity','Enterprise','Galactica','A'),
('video_games','extreme','Cuphead art style inspired by?','80s cartoons','30s cartoons','60s cartoons','Anime','B');
